Assignment-war/src/fit5042/tutex/mbeans/PropertyManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 */
package fit5042.tutex.mbeans;

import fit5042.tutex.repository.PropertyRepository;
import fit5042.tutex.repository.entities.Address;
import fit5042.tutex.repository.entities.ContactPerson;
import fit5042.tutex.repository.entities.Property;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;


@ManagedBean(name = "propertyManagedBean")
@SessionScoped

public class PropertyManagedBean implements Serializable {

    @EJB
    PropertyRepository propertyRepository;

    /**
     * Creates a new instance of PropertyManagedBean
     */
    public PropertyManagedBean() {
    }

    public List<Property> getAllProperties() {
        try {
            List<Property> properties = propertyRepository.getAllProperties();
            return properties;
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void addProperty(Property property) 
    {
        try {
             propertyRepository.addProperty(property);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addContact(ContactPerson contact) 
    {
        try {
             propertyRepository.addContactPerson(contact);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Search a property by Id
     */
    public Property searchPropertyById(int id)
    {
        try {
            return propertyRepository.searchPropertyById(id);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    public ContactPerson searchContactById(int id)
    {
        try {
            return propertyRepository.searchContactById(id);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    public Set<Property> searchPropertyByContactPerson(ContactPerson contactPerson) 
    {
        try {
            return propertyRepository.searchPropertyByContactPerson(contactPerson);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }

    public List<ContactPerson> getAllContactPeople() throws Exception {
    	
    	try {
            return propertyRepository.getAllContactPeople();
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public void removeProperty(int propertyId) 
    {
        try {
            propertyRepository.removeProperty(propertyId);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void removeContact(int id) 
    {
        try {
            propertyRepository.removeContactPerson(id);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void editProperty(Property property)
    {
        try {
            String s = property.getAddress().getStreetNumber();
            Address address = property.getAddress();
            address.setStreetNumber(s);
            property.setAddress(address);
            
            propertyRepository.editProperty(property);
            
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void editContact(ContactPerson contact)
    {
        try {
           
            propertyRepository.editContactPerson(contact);
            
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Contact Person has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addProperty(fit5042.tutex.controllers.Property localProperty) {
    	
        //convert this newProperty which is the local property to entity property
        Property property = convertPropertyToEntity(localProperty);

        try {
            propertyRepository.addProperty(property);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addContactPerson(fit5042.tutex.controllers.ContactPerson localContact) {
    	
        //convert this newProperty which is the local property to entity property
    	ContactPerson contact = new ContactPerson();
    	contact.setConactPersonId(localContact.getConactPersonId());
    	contact.setName(localContact.getName());
    	contact.setPhoneNumber(localContact.getPhoneNumber());

        try {
            propertyRepository.addContactPerson(contact);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    private Property convertPropertyToEntity(fit5042.tutex.controllers.Property localProperty) {
    	
        Property property = new Property(); //entity
        
        property.setCustomerName(localProperty.getCustomerName());
        property.setIndustryType(localProperty.getIndustryType());
        property.setCustomerPhoneNum("0" + localProperty.getCustomerPhoneNum());
        property.setEmail(localProperty.getEmail());
        
        String streetNumber = localProperty.getStreetNumber();
        String streetAddress = localProperty.getStreetAddress();
        String suburb = localProperty.getSuburb();
        String postcode = localProperty.getPostcode();
        String state = localProperty.getState();
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
        property.setAddress(address);
        
        property.setCustomerId(localProperty.getCustomerId());
        property.setTags(localProperty.getTags());
        
        int conactPersonId = localProperty.getConactPersonId();
        String name = localProperty.getName();
        String  phoneNumber = localProperty.getPhoneNumber();
        String type = localProperty.getType();
        
        ContactPerson contactPerson = new fit5042.tutex.repository.entities.ContactPerson(conactPersonId, name, phoneNumber);
        
        if (contactPerson.getConactPersonId() == 0)
            contactPerson = null;
        property.setContactPerson(contactPerson);
        
        return property;
    }
    

}

Assignment-war/WebContent/admin/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Property
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create"/></h1>
                
                <table class="table table-bordered ">
                
                	<tr class="#{!customerName.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="customerName" for="customerName" /></td>
							<td><h:inputText id="customerName" value="#{property.customerName}"
									title="customerName" required="true"
									requiredMessage="Please enter the Customer Name!"
									pt:placeholder="Customer Name" /> <br /> <h:message
									for="customerName"
									class="#{!customerName.valid ? 'label label-warning' : 'none'}" />
							</td>
					</tr>
					<tr class="#{!industryTypee.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="industryType" for="industryType" /></td>
							<td><h:inputText id="industryType" value="#{property.industryType}"
									title="industryType" required="true"
									requiredMessage="Please enter the Industry Type!"
									pt:placeholder="Industry Type" /> <br /> <h:message
									for="industryType"
									class="#{!industryType.valid ? 'label label-warning' : 'none'}" />
							</td>
						</tr>
						<tr class="#{!customerPhoneNum.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="customerPhoneNum" for="customerPhoneNum" /></td>
							<td><h:inputText id="customerPhoneNum" value="#{property.customerPhoneNum}"
									title="customerPhoneNum" required="true"
									maxlength="9"
									requiredMessage="Please enter the Phone Number!"
									validatorMessage="Please enter a 10 digit phone number! "
									converterMessage="Please enter a number"
									pt:placeholder="0123456789" > 
									<f:convertNumber integerOnly="true" /> 
									<f:validateLength minimum="9" maximum="9" />
									</h:inputText> <br /> <h:message
									for="customerPhoneNum"
									class="#{!customerPhoneNum ? 'label label-warning' : 'none'}" />
							</td>
						</tr>
						<tr class="#{!email.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="email" for="email" /></td>
							<td><h:inputText id="email" value="#{property.email}"
									title="email" required="true"
									requiredMessage="Please enter the Email!"
									pt:placeholder="email" /> <br /> <h:message
									for="email"
									class="#{! email? 'label label-warning' : 'none'}" />
							</td>
						</tr>
                   <tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
							<td width="200"><h:outputLabel value="streetNumber"
									for="streetNumber" /></td>
							<td><h:inputText id="streetNumber"
									value="#{property.streetNumber}" title="streetNumber"
									required="true"
									requiredMessage="Please enter the street number!"
									validatorMessage="Please enter a street number between 1 and 1000"
									converterMessage="Please enter a number" pt:placeholder="900">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="1" maximum="1000" />
								</h:inputText> <br /> <h:message for="streetNumber"
									class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
							</td>
						</tr>

						<tr class="#{!streetAddress.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="streetAddress" for="streetAddress" />
							</td>
							<td><h:inputText id="streetAddress"
									value="#{property.streetAddress}" title="streetAddress"
									required="true"
									requiredMessage="Please enter the street address!"
									pt:placeholder="Dandenong Rd" /> <br /> <h:message
									for="streetAddress"
									class="#{!streetAddress.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>

						<tr class="#{!suburb.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="suburb" for="suburb" /></td>
							<td><h:inputText id="suburb" value="#{property.suburb}"
									title="suburb" required="true"
									requiredMessage="Please enter the suburb!"
									pt:placeholder="Caulfield East" /> <br /> <h:message
									for="suburb"
									class="#{!suburb.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>

						<tr class="#{!state.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="state" for="state" /></td>
							<td><h:inputText id="state" value="#{property.state}"
									title="state" size="3" required="true"
									requiredMessage="Please enter the state!" pt:placeholder="VIC" />
								<br /> <h:message for="state"
									class="#{!state.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						<tr class="#{!postcode.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="postcode" for="postcode" /></td>
							<td><h:inputText id="postcode" value="#{property.postcode}"
									title="postcode" required="true"
									requiredMessage="Please enter the postcode!"
									validatorMessage="Please enter a postcode between 0200 and 4700"
									converterMessage="Please enter a number" pt:placeholder="3145">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="200" maximum="4700" />
								</h:inputText> <br /> <h:message for="postcode"
									class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>
						
						<tr>
							<td><h:outputLabel value="Contact Person:" for="contact" /></td>
							<td><h:selectOneMenu id="contact" value="#{property.contactPerson}" >
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItems value="#{propertyManagedBean.allContactPeople}"
										var="c" itemLabel="#{c.name}" itemValue="#{c}" />
								
								</h:selectOneMenu></td>
						</tr>

                    
                    
                </table>
                
                <h:commandButton id="submit" value="Submit" action="#{addProperty.addProperty(property)}" class="btn btn-primary" >
                </h:commandButton>
                <h:link id="close" value="Close" outcome="index.xhtml"
						class="btn btn-primary" />
            	
            </h:form>
			
        </f:view>
            </div>
        </div>
       
    </h:body>
</html>

Assignment-war/WebContent/admin/addContact.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    Add Contact Person
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create"/></h1>
                
                <table class="table table-bordered ">
                
                	<tr class="#{!contactName.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="contactName" for="contactName" /></td>
							<td><h:inputText id="contactName" value="#{contact.name}"
									title="contactName" required="true"
									requiredMessage="Please enter the Contact Person Name!"
									pt:placeholder="contact Name" /> <br /> <h:message
									for="contactName"
									class="#{!contactName.valid ? 'label label-warning' : 'none'}" />
							</td>
					</tr>
					
					<tr class="#{!phoneNum.valid ? 'has-error' : 'none'}">
						<td><h:outputLabel value="phoneNum" for="phoneNum" /></td>
						<td><h:inputText id="phoneNum" value="#{contact.phoneNumber}"
								title="phoneNum" required="true"
								maxlength="9"
								requiredMessage="Please enter the Phone Number!"
								validatorMessage="Please enter a 10 digit phone number! "
								converterMessage="Please enter a number"
								pt:placeholder="0123456789" > 
								<f:convertNumber integerOnly="true" /> 
								<f:validateLength minimum="9" maximum="9" />
								</h:inputText> <br /> <h:message
								for="phoneNum"
								class="#{!phoneNum ? 'label label-warning' : 'none'}" />
						</td>
					</tr>
				

                    
                    
                </table>
                
                <h:commandButton id="submit" value="Submit" action="#{addContact.addContact(contact)}" class="btn btn-primary" >
                </h:commandButton>
                <h:link id="close" value="Close" outcome="contactlist.xhtml"
						class="btn btn-primary" />
            	
            </h:form>
			
        </f:view>
            </div>
        </div>
       
    </h:body>
</html>

Assignment-war/WebContent/admin/contactlist.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

    <h:head>
			<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        	<title>Contact Person List</title> 
        </h:head>
<body> 
<div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    Contact Person  List
                </div>
            </div>
            <h:form id="ContactForm">
                <table class="table table-bordered table-striped">
                    <!-- For each customer contact in properties ArrayList... --> 
                    <tr>
                       <td> 
                           <h:outputLabel id="Id" value="ID"  />
                       </td>
                       <td> 
                           <h:outputLabel id="customerContact" value="Contact Name"  />
                       </td>
                       <td> 
                           <h:outputLabel id="phoneNumber" value="Phone Number"  />
                       </td>
                        <td> 
                           <h:outputLabel id="operation" value="Operation"/>
                       </td>
                     </tr>
                     
                    <ui:repeat id="Myrepeat" value="#{propertyApplication.contacts}"  var="contact" varStatus="status"> 
                        
                        <tr > 
                            <td>
                                <h:outputText value="#{propertyApplication.contacts.get(status.index).conactPersonId}" id="contactID" /> 
                            </td>
        					<td>
                                <h:outputText value="#{propertyApplication.contacts.get(status.index).name}" id="contactName" /> 
                            </td>
                            <td>
                                <h:outputText value="#{propertyApplication.contacts.get(status.index).phoneNumber}" id="contactPhone" /> 
                            </td>
                  
                           
                            <td>
                                <h:link value="View | " outcome="detailContact.xhtml">
                                <!-- pass the parameter to next page, the param name is contactID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="contactID" value="#{status.index + 1}"/>
                                </h:link>

                                <h:link value="Edit | " outcome="editContact.xhtml">
                                <!-- pass the parameter to next page, the param name is contactID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="contactID" value="#{status.index + 1}"/>
                                </h:link>
                                
                                <h:commandLink value="Delete" action="#{removeContact.removeContact(propertyApplication.contacts.get(status.index).conactPersonId)}" disabled="#{propertyApplication.contacts.get(status.index).conactPersonId == null}">
                                </h:commandLink>
                                    
                                <h:outputText value=" "/>
                            </td>
                            
                        </tr> 

                    </ui:repeat> 
                    

                </table>
                
                <div>
                    <h:commandButton id="add" value="Add" action="addContact.xhtml" class="btn btn-primary" />
                
                    <h:commandButton id="viewAll" value="View All" action="#{searchContact.searchAllContact()}" class="btn btn-primary" >
                        <f:param name="Index" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                <div>
                    <h:inputText value="#{searchContact.searchByInt}" id="searchById" required="true" onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "   /> 
                    <h:commandButton id="searchId" value="Search by Id" action="#{searchContact.searchContactById(searchContact.searchByInt)}" class="btn btn-primary" >
                        <f:param name="Index" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                
                </h:form>
                
                <br/>
        		<br/>
        		<h:link outcome = "welcome.xhtml" value = "Back to Home" />
                </div>
</body> 
</html>

Assignment-war/WebContent/admin/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Customer Details
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">

                    <tr>
                        <td width ="150" valign="top">Id:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{propertyController.property.customerId}</h:outputLabel>    
                        </td>
                    </tr>
                     <tr>
                        <td width ="100" valign="top">Customer Name: </td>

                        <td valign="bottom">
                            <h:inputText id = "CustomerName" value="#{propertyController.property.customerName}"  required="true"
                                         validatorMessage="Please enter a valid Customer Name"
                                         requiredMessage="Please enter the Customer Name. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Street number: </td>
                        <td valign="bottom">
                            <h:inputText id = "streetNumber" value="#{propertyController.property.address.streetNumber}" binding="#{streetNumber}" required="true"
                                         validatorMessage="Please enter a valid street number."
                                         requiredMessage="Please enter an street number. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Street address: </td>
                        <td valign="bottom">
                            <h:inputText id = "streetAddress" value="#{propertyController.property.address.streetAddress}" binding="#{streetAddress}" required="true"
                                         validatorMessage="Please enter a valid street address."
                                         requiredMessage="Please enter an street address. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Suburb: </td>
                        <td valign="bottom">
                            <h:inputText id = "suburb" value="#{propertyController.property.address.suburb}" binding="#{suburb}" required="true"
                                         validatorMessage="Please enter a valid suburb."
                                         requiredMessage="Please enter a suburb. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">State: </td>
                        <td valign="bottom">
                            <h:inputText id = "state" value="#{propertyController.property.address.state}" binding="#{state}" required="true"
                                         validatorMessage="Please enter a valid state."
                                         requiredMessage="Please enter a state. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Postcode: </td>
                        <td valign="bottom">
                            <h:inputText id = "postcode" value="#{propertyController.property.address.postcode}" binding="#{postcode}" required="true"
                                         validatorMessage="Please enter a valid postcode."
                                         requiredMessage="Please enter a postcode. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Industry Type: </td>

                        <td valign="bottom">
                            <h:inputText id = "IndustryType" value="#{propertyController.property.industryType}"  required="true"
                                         validatorMessage="Please enter a valid IndustryType"
                                         requiredMessage="Please enter the industry type. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Phone Number: </td>

                        <td valign="bottom">
                            <h:inputText id = "CustomerPhoneNum" value="#{propertyController.property.customerPhoneNum}"  required="true"
                                         validatorMessage="Please enter a valid CustomerPhoneNum"
                                         requiredMessage="Please enter the Customer PhoneNum. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Email: </td>

                        <td valign="bottom">
                            <h:inputText id = "Email" value="#{propertyController.property.email}"  required="true"
                                         validatorMessage="Please enter a valid Email"
                                         requiredMessage="Please enter the Email. "></h:inputText>    
                        </td>
                    </tr>
                   
					<tr>
                        <td width ="100" valign="top">Contact Person: </td>
                        <td>
                            <h:selectOneMenu id="contact" value="#{propertyController.property.contactPerson}" converter="contactPerson">
                                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
                                <f:selectItems value="#{propertyManagedBean.allContactPeople}" var="c"  
                                               itemLabel="#{c.name}" itemValue="#{c}" />
                            </h:selectOneMenu>
                        </td>
                    </tr>       
					
                    </table>
                    
                
                <h:commandButton id="save" value="Save" action="#{propertyManagedBean.editProperty(propertyController.property)}"  class="btn btn-primary" >
                    <f:param name="propertyID" value="#{propertyController.propertyId+1}"/>
                </h:commandButton>
                <h:link id="close" value="Close" outcome="index.xhtml"
						class="btn btn-primary" />
            </h:form>
        </div>
    </h:body>
</html>

Assignment-war/WebContent/admin/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
        <title>Administration</title>
    </h:head>
    <h:body>
        <h1>Welcome to Administration Area</h1>
        <br/>
        <h:link outcome = "index.xhtml" value = "Manage Customers" />
        <br/>
        <h:link outcome = "contactlist.xhtml" value = "Manage Contact Person" />
        <br/>
        <br/>
        <h:link outcome = "/home.xhtml" value = "Back to Navigation" />
    </h:body>
   
</html>